"""
Create a program that will play the “cows and bulls” game with the user. 

The game works like this:

Randomly generate a 4-digit number. 
Ask the user to guess a 4-digit number. 
For every digit that the user guessed correctly in the correct place, 
	they have a “cow”. 
For every digit the user guessed correctly in 
	the wrong place is a “bull.” 
Every time the user makes a guess, 
	tell them how many “cows” and “bulls” they have. 

Once the user guesses the correct number, the game is over. 
Keep track of the number of guesses the user makes 
	throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. 

An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
"""
import random

def cows(randomNumber, guessNumber):
	correct = 0

	for x in range(0,4):
		if(list(randomNumber)[x] == list(guessNumber)[x]):
			correct = correct + 1
	return correct


if __name__ == "__main__":
	guessNumber = '0'
	errorFlag, guessCount = 0, 0, 
	playFlag = True
	randomNumber = str(random.randint(1000,9999))

	print(randomNumber)
	while playFlag:
		while (len(guessNumber) < 4):
			
			if errorFlag:
				print("Error guess is less than 4 digits!")

			guessNumber = input("Please input the 4 digit guess: ")
			errorFlag = 1
			
		guessCount += 1
		correct = cows(randomNumber, guessNumber)

		if correct == 4:
			print("Exact guess! with ", guessCount, " guess/es")
			break
		else:
			print("Cows: ", correct, " Bulls: ", 4-correct)
			errorFlag = 0
			guessNumber = '0'

		play = input("Do you want to continue? If not input 'exit' ")

		if play == 'exit':
				break

	input()